[workspace]
resolver = "2"
members = ["prefer", "prefer_derive"]

[workspace.package]
version = "0.3.2"
edition = "2021"
authors = ["LimpidTech"]
license = "MIT"
repository = "https://github.com/LimpidTech/prefer.rs"
